---
- name: Generate artifact, copy artifact & sql file to files directory
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install jdk,maven,git
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - git
        - openjdk-8-jdk
        - maven
    - name: Clone source code from github
      git:
        repo: 'https://github.com/devopshydclub/vprofile-repo.git'
        dest: ./repo
        version: vp-rem
      register: git_status
    - name: mvn install command to build artifact
      command: "mvn install"
      args:
        chdir: repo
      when: git_status.changed
      register: mvn_info
      #- debug:
      #  msg: "{{mvn_info}}"
    - name: Copy arifacts to files directory
      command: "cp repo/target/vprofile-v2.war files/"

    - name: Copy SQL files to files directory
      command: "cp repo/src/main/resources/db_backup.sql files/"

