---
- name: Install Memcache, Start & enable SVC
  hosts: mcsrvgrp
  gather_facts: no
  tasks:
    - name: Install Memcache
      apt:
        name: memcached
        state: present
        update_cache: yes
        cache_valid_time: 86400
      tags:
       - package
      
    - name: Start & Enable Memcache
      service:
        name: memcached
        state: started
        enabled: yes
      tags:
       - svc

    - name: Enable remote login to mysql svc
      lineinfile:
        path: /etc/memcached.conf
        regexp: '^-l 127.0.0.1'
        line: '-l 0.0.0.0'
        backup: yes
      notify:
        - Restart memcached
      tags:
       - cnf

  handlers:
    - name: Restart memcached
      service:
        name: memcached
        state: restarted
